name: Build Docs

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'

jobs:
  build-deploy-docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Create venv and install deps
        run: |
          pip install --upgrade pip wheel
          pip install -r docs/requirements.txt

      - name: Build Docs
        run: |
          make -C docs
